version: "2.1"
networks:
  aca:
    driver: bridge

services:
  search:
    image: quay.io/acaprojects/elastic
    container_name: elastic
    restart: always
    user: elasticsearch
    networks:
      - aca
    ports:
      - "9200:9200"
    hostname: elastic
    volumes:
     - ./config/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
     - ./config/elastic/logging.yml:/usr/share/elasticsearch/config/logging.yml:ro
     #- $DATA_DIR/elastic:/usr/share/elasticsearch/data:Z
    environment:
      - TZ=$TZ
      - CB_USER=$CB_USER
      - CB_PASS=$CB_PASS
  db:
    image: couchbase:4.6.2
    container_name: couch
    restart: always
    networks:
      - aca
    ports:
      - "8091:8091"
    hostname: couch
    volumes:
      - $DATA_DIR/couch:/opt/couchbase/var:Z
    environment:
      - TZ=$TZ
  engine:
    image: quay.io/acaprojects/engine
    restart: always
    container_name: engine
    networks:
      - aca
    ports:
      - "8080:8080"
    hostname: engine
    depends_on:
      - db
      - search
#    volumes:
#      - ${ACA_DEVICE_MODULES}:/home/aca-apps/aca-device-modules:ro
#      - ${RUBY_ENGINE_APP}:/home/aca-apps/ruby-engine-app:ro
    environment:
      - TZ=$TZ
      - WWW_PORT=$WWW_PORT
      - ELASTIC=elastic
      - ELASTIC_INDEX=$ES_INDEX
      - COUCHBASE_HOST=couch
      - COUCHBASE_BUCKET=$CB_BUCKET
      - COUCHBASE_PASSWORD=$CB_PASS
      - UV_THREADPOOL_SIZE=16
      - ENGINE_NODE_ID=$ENGINE_NODE_ID
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
  # web:
  #   image: yobasystems/alpine-nginx
  #   container_name: nginx
  #   restart: always
  #   networks:
  #     - aca
  #   ports:
  #     - "80:80"
  #   hostname: nginx
  #   depends_on:
  #     - engine
  #   volumes:
  #     - ./config/nginx/nginx.conf/:/etc/nginx/nginx.conf:ro
  #     - ./www/:/etc/nginx/www:ro
  #   environment:
  #     - TZ=$TZ