version: "2.1"
networks:
  aca:
    driver: bridge  
    ipam:
      driver: default
      config:
      - subnet: 172.31.231.0/24
        gateway: 172.31.231.1

volumes:
  elastic-data:
  couch-data:

services:
  elastic:
    image: aca0/elastic
    container_name: elastic
    restart: always
    user: elasticsearch
    networks:
      aca:
        ipv4_address: 172.31.231.2
    ports:
      - "9200:9200"
    hostname: elastic
    logging:
      options:
       max-size: 99m
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - TZ=$TZ
      - CB_USER=$CB_USER
      - CB_PASS=$CB_PASS
    healthcheck:
      test: wget --quiet --spider http://localhost:9200
  couch:
    image: couchbase:community-4.5.1
    container_name: couch
    restart: always
    networks:
      aca:
        ipv4_address: 172.31.231.3
    ports:
      - "8091:8091"
    hostname: couch
    logging:
      options:
       max-size: 99m
    volumes:
      - couch-data:/opt/couchbase/var
    environment:
      - TZ=$TZ
    healthcheck:
      test: wget --quiet --spider http://localhost:8092
  engine:
    image: $DOCKER_ENGINE
    restart: always
    container_name: engine
    command: engine-dev
    networks:
      aca:
        ipv4_address: 172.31.231.4
    ports:
      - "8080:8080"
    hostname: engine
    logging:
      options:
       max-size: 99m
    depends_on:
      - couch
      - elastic
    volumes:
      - ./aca-device-modules:/home/aca-apps/aca-device-modules:ro
    environment:
      - TZ=$TZ
      - WWW_PORT=$WWW_PORT
      - DEV_PORT=$DEV_PORT
      - RAILS_ENV=$RAILS_ENV
      - ELASTIC=elastic
      - ELASTIC_INDEX=$ES_INDEX
      - COUCHBASE_HOST=couch
      - COUCHBASE_BUCKET=$CB_BUCKET
      - COUCHBASE_PASSWORD=$CB_PASS
      - UV_THREADPOOL_SIZE=4
      - COAUTH_NO_SSL=true
      - ENGINE_NODE_ID=$ENGINE_NODE_ID
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
    healthcheck:
      test: wget --quiet --spider http://localhost:8080/auth/authority
      interval: 120s
  nginx:
    image: yobasystems/alpine-nginx:git
    container_name: nginx
    restart: always
    networks:
      aca:
        ipv4_address: 172.31.231.5
    ports:
      - "80:80"
    hostname: nginx
    logging:
      options:
       max-size: 99m
    depends_on:
      - engine
    volumes:
      - ./config/nginx/nginx.conf/:/etc/nginx/nginx.conf:ro
      - ./www/:/etc/nginx/html
    environment:
      - TZ=$TZ
      - WWW_PORT=$WWW_PORT
      - REPO=https://github.com/acaprojects/engine-front
    healthcheck:
      test: wget --quiet --spider http://localhost