version: "2.1"
networks:
  aca:
    driver: bridge

services:
  search:
    image: quay.io/acaprojects/elastic
    container_name: elastic
    restart: unless-stopped
    user: elasticsearch
    networks:
      - aca
    ports:
      - "9200:9200"
    hostname: elastic
    volumes:
     - ./config/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
     - ./config/elastic/logging.yml:/usr/share/elasticsearch/config/logging.yml:ro
     - ~/data/elastic:/usr/share/elasticsearch/data:z
    environment:
      - TZ=$TZ
      - CB_USER=$CB_USER
      - CB_PASS=$CB_PASS
  db:
    image: couchbase:4.6.2
    container_name: couch
    restart: unless-stopped
    networks:
      - aca
    ports:
      - "8091:8091"
    hostname: couch
    volumes:
      - ~/data/couch:/opt/couchbase/var:z
    environment:
      - TZ=$TZ
  app:
    image: quay.io/acaprojects/engine
    restart: unless-stopped
    container_name: engine
    networks:
      - aca
    ports:
      - "8080:8080"
    hostname: engine
    depends_on:
      - db
      - search
#    volumes:
#      - ${ACA_DEVICE_MODULES}:/home/aca-apps/aca-device-modules:ro
#      - ${RUBY_ENGINE_APP}:/home/aca-apps/ruby-engine-app:ro
    environment:
      - TZ=$TZ
      - WWW_PORT=$WWW_PORT
      - ELASTIC=elastic
      - ELASTIC_INDEX=$ES_INDEX
      - COUCHBASE_HOST=couch
      - COUCHBASE_BUCKET=$CB_BUCKET
      - COUCHBASE_PASSWORD=$CB_PASS
      - UV_THREADPOOL_SIZE=16
