network.bind_host: _site_
network.publish_host: _site_
discovery.zen.ping.multicast.enabled: false

# Set a cluster name and password for couchbase
cluster.name: aca
couchbase.password: ${CB_PASS}
couchbase.username: ${CB_USER}
couchbase.ignoreFailures: true

#
# Document Mappings
#
couchbase.typeSelector: org.elasticsearch.transport.couchbase.capi.RegexTypeSelector

couchbase.typeSelector.documentTypesRegex.sgrp: ^sgrp(-|_).+$
couchbase.typeSelector.documentTypesRegex.user: ^user(-|_).+$
couchbase.typeSelector.documentTypesRegex.grp: ^grp(-|_).+$
couchbase.typeSelector.documentTypesRegex.inv: ^inv(-|_).+$

couchbase.typeSelector.documentTypesRegex.loc: ^loc(-|_).+$
couchbase.typeSelector.documentTypesRegex.art: ^art(-|_).+$
couchbase.typeSelector.documentTypesRegex.com: ^com(-|_).+$

couchbase.typeSelector.documentTypesRegex.cha: ^cha(-|_).+$

couchbase.typeSelector.documentTypesRegex.entry: ^entry(-|_).+$
couchbase.typeSelector.documentTypesRegex.ply: ^ply(-|_).+$
couchbase.typeSelector.documentTypesRegex.plr: ^plr(-|_).+$
couchbase.typeSelector.documentTypesRegex.pgj: ^pgj(-|_).+$

couchbase.typeSelector.documentTypesRegex.one: ^one(-|_).+$
couchbase.typeSelector.documentTypesRegex.ugj: ^ugj(-|_).+$    # User group join
couchbase.typeSelector.documentTypesRegex.cgj: ^cgj(-|_).+$    # channel group join
couchbase.typeSelector.documentTypesRegex.apj: ^apj(-|_).+$

# Associate user group joins with groups
couchbase.parentSelector.documentTypeParentFields.ugj: doc.group_id
couchbase.documentTypeRoutingFields.ugj: doc.group_id

# Associate channels with groups
couchbase.parentSelector.documentTypeParentFields.cha: doc.group_id
couchbase.documentTypeRoutingFields.cha: doc.group_id

# Associate channel group joins with groups
couchbase.parentSelector.documentTypeParentFields.cgj: doc.group_id
couchbase.documentTypeRoutingFields.cgj: doc.group_id

# Associate articles with groups
couchbase.parentSelector.documentTypeParentFields.art: doc.group_id
couchbase.documentTypeRoutingFields.art: doc.group_id

# Associate playlists with groups
couchbase.parentSelector.documentTypeParentFields.ply: doc.group_id
couchbase.documentTypeRoutingFields.ply: doc.group_id

# Associate invitations with groups
couchbase.parentSelector.documentTypeParentFields.inv: doc.group_id
couchbase.documentTypeRoutingFields.inv: doc.group_id

# Associate comments with articles
couchbase.parentSelector.documentTypeParentFields.com: doc.article_id
couchbase.documentTypeRoutingFields.com: doc.group_id

# -------------------
# ACA Engine Mappings:
# -------------------
couchbase.typeSelector.documentTypesRegex.mod: ^mod(-|_).+$
couchbase.typeSelector.documentTypesRegex.alog: ^alog(-|_).+$
couchbase.typeSelector.documentTypesRegex.sys: ^sys(-|_).+$
couchbase.typeSelector.documentTypesRegex.dep: ^dep(-|_).+$
couchbase.typeSelector.documentTypesRegex.zone: ^zone(-|_).+$
couchbase.typeSelector.documentTypesRegex.trigger: ^trigger(-|_).+$
couchbase.typeSelector.documentTypesRegex.trig: ^trig(-|_).+$
couchbase.typeSelector.documentTypesRegex.stats: ^zzz(-|_).+$
couchbase.typeSelector.documentTypesRegex.edge: ^edge(-|_).+$
couchbase.typeSelector.documentTypesRegex.disc: ^disc-.+$   # Disc is different to all the other IDs

# Module to dependency mapping
couchbase.parentSelector.documentTypeParentFields.mod: doc.dependency_id
couchbase.documentTypeRoutingFields.mod: doc.dependency_id

# Trigger mappings
couchbase.parentSelector.documentTypeParentFields.trig: doc.trigger_id
couchbase.documentTypeRoutingFields.trig: doc.trigger_id
