# Elasticsearch: Upload couchbase template and initialise DEV 'aca' index
- name: Elasticsearch Initialisation
  hosts: default

  vars:
    es_host: localhost
    es_port: 9200
    es_template: /vagrant/config/elastic/es_template.json
    es_shards: 1
    es_replicas: 0

  tasks:
  - name: Check for aca index
    uri:      
      url: "http://{{ es_host }}:{{ es_port }}/{{ es_index }}"
      status_code: 200, 404
    register: aca_index_result
    delay: 3
    retries: 9

  - name: Check for couchbase template
    uri:      
      url: "http://{{ es_host }}:{{ es_port }}/_template/couchbase"
      status_code: 200, 404
    register: couchbase_template_result
    delay: 3
    retries: 9

  - name: Upload Couchbase template
    when: couchbase_template_result.status == 404
    command: "curl -v -X PUT {{es_host}}:{{es_port}}/_template/couchbase -d @{{es_template}}"

  - name: Add aca index
    when: aca_index_result.status == 404
    uri: 
      url: "http://{{es_host}}:{{es_port}}/{{es_index}}"
      method: PUT
      return_content: yes
      body: "{\"settings\" : {\"index\" : {\"number_of_shards\" : {{es_shards}},\"number_of_replicas\" : {{es_replicas}}}}}"
      body_format: json
      status_code: 200