# Initialise ACAEngine
- name: Engine Initialisation
  hosts: all

  vars:
    engine_password: "{{ ansible_env.CB_PASS }}"
    www_port: "{{ ansible_env.WWW_PORT }}"
    dev_port: "{{ ansible_env.DEV_PORT }}"

  tasks:
    - name: Create Node document
      shell: sg docker -c "docker exec engine rake migrate:nodes"
      register: result
      until: result.rc == 0
      retries: 9
      delay: 1
      ignore_errors: yes

    - name: Add local authority
      shell: sg docker -c "docker exec engine rake domain:add_authority[engine,http://localhost,{{ engine_password }}]"

    - name: Add backoffice app on DEV_PORT
      shell: sg docker -c "docker exec engine rake domain:add_app[backoffice-dev,http://localhost:{{ dev_port }}]"

    - name: Add backoffice app on WWW_PORT
      shell: sg docker -c "docker exec engine rake domain:add_app[backoffice,http://localhost:{{ www_port }}]"
      when: www_port != "80"

    - name: Add backoffice app on 80
      shell: sg docker -c "docker exec engine rake domain:add_app[backoffice,http://localhost]"
      when: www_port == "80"

    - name: Restart Engine with new settings
      shell: sg docker -c "docker-compose restart engine"
      args:
        chdir: /vagrant

    - name: Scan for Drivers
      shell: sg docker -c "docker exec engine rake discover:drivers"
      register: result
      until: result.rc == 0
      retries: 9
      delay: 1
      ignore_errors: yes

    - name: Create Demo System
      shell: sg docker -c "docker exec engine rake demo:system1"
