- name: Generate Secets
  hosts: all

  tasks:
    - name: Generate Engine Node ID
      shell: grep -q -F 'ENGINE_NODE_ID' ../.env || echo  "\nENGINE_NODE_ID=edge-$(openssl rand -base64 8)"  | tr -d '/' >> ../.env

    - name: Generate Engine SECRET_KEY_BASE if not present
      shell: grep -q -F 'SECRET_KEY_BASE' ../.env || echo  "\nSECRET_KEY_BASE=$(openssl rand -base64 45)" | tr -d '/' >> ../.env
