- name: Generate Secrets
  hosts: all

  tasks:
    - name: Generate Couchbase password
      shell: grep -q -F 'CB_PASS' ../.env || echo "CB_PASS=$(openssl rand -base64 10 | cut -c -10 | tr -d '/+')" >> ../.env

    - name: Generate Engine Node ID
      shell: grep -q -F 'ENGINE_NODE_ID' ../.env || echo "ENGINE_NODE_ID=edge-$(openssl rand -base64 10 | cut -c -10 | tr -d '/+')" >> ../.env

    - name: Generate Engine SECRET_KEY_BASE
      shell: grep -q -F 'SECRET_KEY_BASE' ../.env || echo "SECRET_KEY_BASE=$(openssl rand -base64 45)" | tr -d '/+' >> ../.env
