- name: Generate Secets 
  hosts: default

  tasks:
    - name: Generate Couchbase / Elastic / Engine Admin Password if not already in .env
      shell: grep -q -F 'CB_PASS' ../.env || echo "\n\nCB_PASS=$(openssl rand -base64 12)" | tr -d '/' >> ../.env

    - name: Generate Engine Node ID
      shell: grep -q -F 'ENGINE_NODE_ID' ../.env || echo  "ENGINE_NODE_ID=edge-$(openssl rand -base64 8)"  | tr -d '/' >> ../.env

    - name: Generate Engine SECRET_KEY_BASE if not present
      shell: grep -q -F 'SECRET_KEY_BASE' ../.env || echo  SECRET_KEY_BASE=$(openssl rand -base64 45) | tr -d '/' >> ../.env
